**Autores:** Irene Condado Alcantarilla, Miguel Ángel Moreno Delgado y Elena Suárez Serrano

# **Procesamiento y limpieza de datos - Kiva Crowdfunding**

Este proyecto tiene como objetivo preparar y limpiar el dataset de Kiva Crowdfunding para su posterior análisis.

Se trabaja con datos de microfinanciación proporcionados por la organización Kiva, aplicando procesos de análisis, diagnóstico y limpieza de datos.

Cada fila del dataset representa un préstamo registrado en la plataforma.

## **Importar datos**

Se carga el dataset de Kiva Crowdfunding desde un archivo CSV.

Se crea una copia del dataset original (`df_raw`) para conservar una versión sin modificar que permita comparar los cambios realizados durante el proceso de limpieza.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_kiva = pd.read_csv('/content/kiva_loans.csv')
df_raw = df_kiva.copy()

Para ir viendo la información vamos a cargar las 5 primeras filas con el comando `.head()`.

In [ ]:
df_kiva.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334.0,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245.0,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16,NaN,female,monthly,2014-01-01

## **Análisis exploratorio inicial**

Se realiza una primera inspección del dataset para comprender su tamaño, estructura y tipos de datos.

Este análisis permite obtener una visión general del conjunto de datos antes de realizar un diagnóstico más detallado.

In [ ]:
df_kiva.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671205 entries, 0 to 671204
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  671205 non-null  int64
 1   funded_amount       671205 non-null  float64
 2   loan_amount         671205 non-null  float64
 3   activity            671205 non-null  object
 4   sector              671205 non-null  object
 5   use                 666973 non-null  object
 6   country_code        671197 non-null  object
 7   country             671205 non-null  object
 8   region              614405 non-null  object
 9   currency            671205 non-null  object
 10  partner_id          657698 non-null  float64
 11  posted_time         671205 non-null  object
 12  disbursed_time      668809 non-null  object
 13  funded_time         622874 non-null  object
 14  term_in_months      671205 non-null  float64
 15  lender_count        671205 non-null  int64
 16  tags                499789 non-null  object
 17  borrower_genders    666984 non-null  object
 18  repayment_interval  671205 non-null  object
 19  date                671205 non-null  object
dtypes: float64(4), int64(2), object(14)
memory usage: 102.4+ MB

In [ ]:
len(df_kiva)

671205

In [ ]:
df_kiva.shape

(671205, 20)

In [ ]:
df_kiva.dtypes

id                      int64
funded_amount         float64
loan_amount           float64
activity               object
sector                 object
use                    object
country_code           object
country                object
region                 object
currency               object
partner_id            float64
posted_time            object
disbursed_time         object
funded_time            object
term_in_months        float64
lender_count            int64
tags                   object
borrower_genders       object
repayment_interval     object
date                   object
dtype: object

In [ ]:
df_kiva.columns

Index(['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use',
       'country_code', 'country', 'region', 'currency', 'partner_id',
       'posted_time', 'disbursed_time', 'funded_time', 'term_in_months',
       'lender_count', 'tags', 'borrower_genders', 'repayment_interval',
       'date'],
      dtype='object')

In [ ]:
df_kiva.describe()

,id,funded_amount,loan_amount,partner_id,term_in_months,lender_count
count,6.712050e+05,671205.000000,671205.000000,657698.000000,671205.000000,671205.000000
mean,9.932486e+05,785.995061,842.397107,178.199616,13.739022,20.590922
std,1.966113e+05,1130.398941,1198.660073,94.247581,8.598919,28.459551
min,6.530470e+05,0.000000,25.000000,9.000000,1.000000,0.000000
25%,8.230720e+05,250.000000,275.000000,126.000000,8.000000,7.000000
50%,9.927800e+05,450.000000,500.000000,145.000000,13.000000,13.000000
75%,1.163653e+06,900.000000,1000.000000,204.000000,14.000000,24.000000
max,1.340339e+06,100000.000000,100000.000000,536.000000,158.000000,2986.000000

Observaciones iniciales

- El dataset contiene 671.205 filas y 20 columnas, lo que indica un volumen de datos considerable.

- Se observa una mezcla de variables numéricas (`funded_amount`, `loan_amount`, `lender_count`) y de tipo `object` (`sector`, `country`, `repayment_interval`).

- Varias columnas que representan fechas (`posted_time`, `disbursed_time`, `funded_time`, `date`) están almacenadas como tipo `object`.`

- La columna `partner_id` y `term_in_months` están almacenada como tipo `float64`.

- La columna `id` parece ser un identificador único para cada préstamo.

- El resumen estadístico nos muestra que las variables `funded_amount` y `loan_amount` presentan rangos amplios entre valores mínimos y máximos. La variable `lender_count` también muestra una gran dispersión, con valores que van desde 0 hasta valores muy elevados.

## **Diagnóstico de problemas**

En esta sección se analizan los principales problemas del dataset antes de aplicar cualquier transformación.

El objetivo es identificar inconsistencias, valores faltantes, duplicados, problemas de formato y posibles valores atípicos.

In [ ]:
df_kiva.isnull().sum()

id                         0
funded_amount              0
loan_amount                0
activity                   0
sector                     0
use                     4232
country_code               8
country                    0
region                 56800
currency                   0
partner_id             13507
posted_time                0
disbursed_time          2396
funded_time            48331
term_in_months             0
lender_count               0
tags                  171416
borrower_genders        4221
repayment_interval         0
date                       0
dtype: int64

In [ ]:
df_kiva.count()

id                    671205
funded_amount         671205
loan_amount           671205
activity              671205
sector                671205
use                   666973
country_code          671197
country               671205
region                614405
currency              671205
partner_id            657698
posted_time           671205
disbursed_time        668809
funded_time           622874
term_in_months        671205
lender_count          671205
tags                  499789
borrower_genders      666984
repayment_interval    671205
date                  671205
dtype: int64

Se observa la presencia de valores nulos en varias columnas del dataset.

Las columnas con mayor número de valores faltantes son:

- `tags`: 171.416 valores nulos
- `region`: 56.800 valores nulos
- `funded_time`: 48.331 valores nulos
- `partner_id`: 13.507 valores nulos
- `use`: 4.232 valores nulos
- `borrower_genders`: 4.221 valores nulos
- `disbursed_time`: 2.396 valores nulos
- `country_code`: 8 valores nulos

Será necesario analizar cada columna de forma individual para decidir el tratamiento más adecuado (eliminación, imputación o conservación).

In [ ]:
df_kiva.duplicated().sum()

np.int64(0)

In [ ]:
df_kiva[df_kiva.duplicated()]

Empty DataFrame
Columns: [id, funded_amount, loan_amount, activity, sector, use, country_code, country, region, currency, partner_id, posted_time, disbursed_time, funded_time, term_in_months, lender_count, tags, borrower_genders, repayment_interval, date]
Index: []

Duplicados

No se han encontrado filas duplicadas en el dataset, por lo que cada registro corresponde a un préstamo único.

Esto tiene sentido porque la columna `id` funciona como identificador de cada préstamo.

In [ ]:
df_kiva.dtypes

id                      int64
funded_amount         float64
loan_amount           float64
activity               object
sector                 object
use                    object
country_code           object
country                object
region                 object
currency               object
partner_id            float64
posted_time            object
disbursed_time         object
funded_time            object
term_in_months        float64
lender_count            int64
tags                   object
borrower_genders       object
repayment_interval     object
date                   object
dtype: object

Tipos de datos incorrectos

Se identifican varios aspectos relevantes en los tipos de datos del dataset:

- Las columnas relacionadas con fechas (`posted_time`, `disbursed_time`, `funded_time`, `date`) están almacenadas como tipo `object`, por lo que será necesario convertirlas a formato `datetime`.

- Las columnas `partner_id` y `term_in_months` están almacenadas como tipo `float64`, probablemente debido a la presencia de valores nulos. Será necesario revisar su tipo en la fase de limpieza para decidir si deben mantenerse como numéricas o transformarse.

- El resto de variables de tipo `object` corresponden a variables categóricas o textuales, cuyo contenido deberá revisarse en fases posteriores.

In [ ]:
df_kiva.select_dtypes(include="object").head()

,activity,sector,use,country_code,country,region,currency,posted_time,disbursed_time,funded_time,tags,borrower_genders,repayment_interval,date
0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,NaN,female,irregular,2014-01-01
1,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,NaN,"female, female",irregular,2014-01-01
2,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,"user_favorite, user_favorite",female,bullet,2014-01-01
3,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,NaN,female,irregular,2014-01-01
4,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,NaN,female,monthly,2014-01-01

Inconsistencias en variables tipo `object`

Se observan varios patrones relevantes:

- Variabilidad en el formato de algunas variables textuales, como `use`, donde se encuentran diferencias en capitalización (mayúsculas/minúsculas) y estilo de escritura.

- Presencia de múltiples valores en una misma celda en variables como `borrower_genders` y `tags`, lo que indica que no se trata de categorías simples, sino de listas de valores concatenados.

- Variables categóricas como `country`, `sector` o `currency` presentan una estructura más uniforme, aunque deberán revisarse posibles inconsistencias menores (espacios, formato o duplicados implícitos).

In [ ]:
df_kiva.describe()

,id,funded_amount,loan_amount,partner_id,term_in_months,lender_count
count,6.712050e+05,671205.000000,671205.000000,657698.000000,671205.000000,671205.000000
mean,9.932486e+05,785.995061,842.397107,178.199616,13.739022,20.590922
std,1.966113e+05,1130.398941,1198.660073,94.247581,8.598919,28.459551
min,6.530470e+05,0.000000,25.000000,9.000000,1.000000,0.000000
25%,8.230720e+05,250.000000,275.000000,126.000000,8.000000,7.000000
50%,9.927800e+05,450.000000,500.000000,145.000000,13.000000,13.000000
75%,1.163653e+06,900.000000,1000.000000,204.000000,14.000000,24.000000
max,1.340339e+06,100000.000000,100000.000000,536.000000,158.000000,2986.000000

Análisis de variables numéricas

Las variables numéricas muestran una alta variabilidad en el dataset.

`funded_amount` y `loan_amount` presentan valores muy dispersos, con diferencias importantes entre valores bajos y altos, lo que sugiere la posible presencia de outliers.

En `loan_amount` y `lender_count` se observan valores máximos muy alejados de los valores habituales, lo que refuerza esta idea.

En varias variables, la media es mayor que la mediana, lo que indica la presencia de algunos valores altos que influyen en el promedio.

`term_in_months` muestra variación, aunque menos extrema en comparación con otras variables.

Por último, `partner_id` presenta valores numéricos coherentes, pero su uso es más adecuado como identificador que como variable numérica para análisis.

Estos aspectos se revisarán en la fase de limpieza, donde se decidirá si deben ser tratados, transformados o mantenidos según su relevancia.

## **Transformaciones y limpieza**

En esta fase se aplican las transformaciones necesarias para preparar el dataset, corrigiendo tipos de datos, gestionando valores faltantes y normalizando la información para su posterior análisis.

In [ ]:
df_kiva.dtypes

id                      int64
funded_amount         float64
loan_amount           float64
activity               object
sector                 object
use                    object
country_code           object
country                object
region                 object
currency               object
partner_id            float64
posted_time            object
disbursed_time         object
funded_time            object
term_in_months        float64
lender_count            int64
tags                   object
borrower_genders       object
repayment_interval     object
date                   object
dtype: object

In [ ]:
df_kiva['posted_time'] = pd.to_datetime(df_kiva['posted_time'], format='ISO8601')
df_kiva['disbursed_time'] = pd.to_datetime(df_kiva['disbursed_time'], format='ISO8601')
df_kiva['funded_time'] = pd.to_datetime(df_kiva['funded_time'], format='ISO8601')
df_kiva['date'] = pd.to_datetime(df_kiva['date'], format='ISO8601')

In [ ]:
df_kiva['term_in_months'] = pd.to_numeric(df_kiva['term_in_months'], errors='coerce').astype('Int64')
df_kiva['partner_id'] = pd.to_numeric(df_kiva['partner_id'], errors='coerce').astype('Int64')

In [ ]:
df_kiva.dtypes

id                                  int64
funded_amount                     float64
loan_amount                       float64
activity                           object
sector                             object
use                                object
country_code                       object
country                            object
region                             object
currency                           object
partner_id                          Int64
posted_time           datetime64[ns, UTC]
disbursed_time        datetime64[ns, UTC]
funded_time           datetime64[ns, UTC]
term_in_months                      Int64
lender_count                        int64
tags                               object
borrower_genders                   object
repayment_interval                 object
date                       datetime64[ns]
dtype: object

In [ ]:
df_kiva.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12,12,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11,14,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43,6,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11,8,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14,16,NaN,female,monthly,2014-01-01

En este bloque se revisan y corrigen los tipos de datos del dataset. Primero se inspeccionan con `df_kiva.dtypes`, luego se convierten las columnas de fecha (`posted_time`, `disbursed_time`, `date`) a formato datetime para facilitar su análisis temporal. También se transforman `term_in_months` y `partner_id` a tipo numérico, convirtiendo valores no válidos en nulos y usando un tipo entero que los permite. Finalmente, se vuelve a comprobar la estructura y se visualizan los datos para confirmar que las conversiones se han realizado correctamente.

In [ ]:
df_kiva = df_kiva.drop_duplicates()

Se eliminan duplicados por seguridad, aunque previamente no se habían detectado registros repetidos.

In [ ]:
# Ver valores nulos en la columna 'tag'
df_kiva['tags'].isnull().sum()

np.int64(171416)

In [ ]:
# Contar valores de la columna
df_kiva['tags'].value_counts(dropna=False)

tags
NaN                                                                                                171416
user_favorite                                                                                       27088
#Parent, #Woman Owned Biz                                                                           16597
#Woman Owned Biz                                                                                    12557
#Parent                                                                                             11671
                                                                                                    ...
user_favorite, #Animals, #Repeat Borrower, #Elderly, #Parent                                            1
#Animals, #Schooling, #Low-profit FP, #Repeat Borrower, #Woman Owned Biz                                1
#Single, #Female Education, #Repeat Borrower                                                            1
#Unique, #Interesting Photo, #Parent, user_favorite, user_favorite                                      1
#Woman Owned Biz, #Parent, #Single Parent, #Health and Sanitation, user_favorite, user_favorite         1
Name: count, Length: 86720, dtype: int64

In [ ]:
# Eliminar la columna 'tag'
df_kiva = df_kiva.drop(columns=['tags'])

In [ ]:
# Comprobar que la columna ya no existe
'tags' in df_kiva.columns

False

Se analiza la columna tag, observando que contiene una gran cantidad de valores nulos y que no aporta información relevante para el análisis. Por ello, se decide eliminarla del dataset utilizando `drop()`. Finalmente, se verifica que la columna ha sido eliminada correctamente comprobando la lista de columnas del DataFrame.

In [ ]:
# Ver valores nulos en la columna 'region'
df_kiva['region'].isnull().sum()

np.int64(56800)

In [ ]:
# Contar valores antes de limpiar
df_kiva['region'].value_counts(dropna=False)

region
NaN                                              56800
Kaduna                                           10000
Lahore                                            7178
Rawalpindi                                        4496
Cusco                                             3841
                                                 ...
San Jose Santiago City                               1
Nor Kesaria village, Armavir region                  1
Mumbwa                                               1
Tungawan Tambulig ZDS                                1
p-4, biasong, lopez jaena, misamis occidental        1
Name: count, Length: 12696, dtype: int64

In [ ]:
# Rellenar valores nulos con 'Unknown'
df_kiva['region'] = df_kiva['region'].fillna('Unknown')

In [ ]:
# Verificar que no hay nulos
df_kiva['region'].isnull().sum()

np.int64(0)

In [ ]:
# Contar valores después de limpiar
df_kiva['region'].value_counts()

region
Unknown                                          56800
Kaduna                                           10000
Lahore                                            7178
Rawalpindi                                        4496
Cusco                                             3841
                                                 ...
San Jose Santiago City                               1
Nor Kesaria village, Armavir region                  1
Mumbwa                                               1
Tungawan Tambulig ZDS                                1
p-4, biasong, lopez jaena, misamis occidental        1
Name: count, Length: 12696, dtype: int64

Se analiza la columna region, detectando la presencia de valores nulos. Dado que se trata de una variable categórica relevante para el análisis geográfico, se decide imputar estos valores con la etiqueta "Unknown" en lugar de eliminarlos. De este modo, se evita la pérdida de información y se mantiene la coherencia del dataset, permitiendo identificar fácilmente los registros sin región definida.

In [ ]:
# Ver valores nulos en la columna
df_kiva['borrower_genders'].isnull().sum()

np.int64(4221)

In [ ]:
# Ver tamaño del dataset antes
df_kiva.shape

(671205, 19)

In [ ]:
# Eliminar filas con valores nulos en 'borrower_genders'
df_kiva = df_kiva.dropna(subset=['borrower_genders'])

In [ ]:
# Verificar tamaño después
df_kiva.shape

(666984, 19)

In [ ]:
# Comprobar que ya no hay nulos
df_kiva['borrower_genders'].isnull().sum()

np.int64(0)

Se analiza la columna `borrower_genders`, detectando la presencia de valores nulos. Dado que esta variable se considera relevante para el análisis, se decide eliminar las filas que no contienen información en dicha columna mediante `dropna(subset=...)`. Antes y después de la eliminación se comprueba el tamaño del dataset para evaluar el impacto de la operación. Finalmente, se verifica que ya no existen valores nulos en esta variable, asegurando la consistencia de los datos para el análisis posterior.

In [ ]:
# Ver valores nulos en la columna
df_kiva['partner_id'].isnull().sum()

np.int64(13088)

In [ ]:
# Ver tamaño del dataset antes
df_kiva.shape

(666984, 19)

In [ ]:
# Eliminar la columna 'partner_id'
df_kiva = df_kiva.drop(columns=['partner_id'])

In [ ]:
# Verificar que la columna ya no existe
'partner_id' in df_kiva.columns

False

In [ ]:
# Ver tamaño después
df_kiva.shape

(666984, 18)

Se analiza la columna `partner_id`, observando que presenta un alto número de valores nulos y que no aporta información relevante para el objetivo del análisis. Por este motivo, se decide eliminarla del dataset mediante `drop()`. Antes y después de la eliminación se revisa la estructura del dataset para asegurar que el cambio se ha aplicado correctamente y no afecta al resto de variables.

In [ ]:
# Filtramos los registros donde la fecha de desembolso es anterior a la de publicación
# Esto representa una inconsistencia lógica en el ciclo del préstamo
df_inconsistentes = df_kiva[df_kiva['disbursed_time'] < df_kiva['posted_time']]

# Mostramos cuántos registros cumplen esta condición (inconsistencias detectadas)
df_inconsistentes.shape

(621052, 18)

In [ ]:
# Visualizamos ejemplos de las inconsistencias detectadas
df_inconsistentes[['posted_time', 'disbursed_time']].head(10)

                 posted_time            disbursed_time
0  2014-01-01 06:12:39+00:00 2013-12-17 08:00:00+00:00
1  2014-01-01 06:51:08+00:00 2013-12-17 08:00:00+00:00
2  2014-01-01 09:58:07+00:00 2013-12-17 08:00:00+00:00
3  2014-01-01 08:03:11+00:00 2013-12-24 08:00:00+00:00
4  2014-01-01 11:53:19+00:00 2013-12-17 08:00:00+00:00
6  2014-01-01 09:51:02+00:00 2013-12-16 08:00:00+00:00
7  2014-01-01 11:46:01+00:00 2013-12-20 08:00:00+00:00
8  2014-01-01 11:49:43+00:00 2013-12-20 08:00:00+00:00
9  2014-01-01 05:41:03+00:00 2013-12-17 08:00:00+00:00
10 2014-01-01 07:32:39+00:00 2013-12-24 08:00:00+00:00

In [ ]:
# Se elimina la columna 'disbursed_time' del dataset
df_kiva = df_kiva.drop(columns=['disbursed_time'])

In [ ]:
# Comprobación de que la columna ha sido eliminada correctamente
'disbursed_time' in df_kiva.columns

False

Se decide eliminar la columna `disbursed_time` del dataset debido a la presencia de inconsistencias detectadas en su relación temporal con posted_time. Dado que esta variable no se utilizará en el análisis principal, se opta por su eliminación para simplificar el conjunto de datos y evitar posibles interpretaciones erróneas derivadas de estos desajustes. Finalmente, se verifica que la columna ha sido eliminada correctamente del dataset.

In [ ]:
# Comprobar valores nulos en funded_time
df_kiva['funded_time'].isnull().sum()

np.int64(47649)

Se analiza la columna `funded_time`, observando la presencia de valores nulos. En este caso, se decide no eliminar ni imputar dichos valores, ya que representan préstamos que aún no han sido completamente financiados por los prestamistas. Por lo tanto, los valores nulos tienen un significado relevante dentro del contexto del análisis y deben conservarse para poder estudiar el estado de financiación de los préstamos.

In [ ]:
# Comprobar valores nulos en la columna 'USE'
df_kiva['use'].isnull().sum()

np.int64(11)

In [ ]:
# Ver distribución incluyendo nulos
df_kiva['use'].value_counts(dropna=False)

use
to buy a water filter to provide safe drinking water for their family.                                                  5217
to buy a water filter to provide safe drinking water for her family.                                                    4082
To buy a water filter to provide safe drinking water for their family.                                                  2141
to build a sanitary toilet for her family.                                                                              1708
to build a sanitary toilet for her family                                                                               1599
                                                                                                                        ...
to launch her own shoe store in her village                                                                                1
to rent an apartment to locate her cosmetics business.                                                                     1
to renovate her store and buy more groceries to sell.                                                                      1
to buy the various tools and supplies wholesale (hair treatments, dyes, shampoo, and conditioner, among other items)       1
to increase her quantity of clothes to sell.                                                                               1
Name: count, Length: 424913, dtype: int64

In [ ]:
# Rellenar valores nulos con 'Unknown'
df_kiva['use'] = df_kiva['use'].fillna('Unknown')

In [ ]:
# Comprobar que ya no hay nulos
df_kiva['use'].isnull().sum()

np.int64(0)

Se analiza la columna `use`, detectando la presencia de valores nulos. Para entender mejor su distribución, se revisan los valores antes de la limpieza incluyendo los nulos. Posteriormente, se decide imputar estos valores con la categoría "Unknown", con el objetivo de mantener la integridad del dataset sin perder información relevante. Finalmente, se verifica que los valores nulos han sido correctamente reemplazados.

In [ ]:
# Ver valores nulos en la columna 'country_code'
df_kiva['country_code'].isnull().sum()

np.int64(8)

Se analiza la columna `country_code`, identificando la presencia de valores nulos en el dataset. En este caso, se decide no modificar ni imputar dichos valores, ya que representan información potencialmente relevante y su tratamiento podría requerir una lógica más compleja basada en otras variables del dataset.

Como mejora del sistema de datos, se propone implementar una validación en la entrada de datos que permita asignar automáticamente el country_code a partir del campo de país correspondiente. De esta forma se evitarían inconsistencias y valores nulos en el futuro, garantizando mayor calidad y estandarización en los datos.

In [ ]:
# Ver ejemplo de valores en las columnas tipo 'object'.
df_kiva.select_dtypes(include='object').head()

,activity,sector,use,country_code,country,region,currency,borrower_genders,repayment_interval
0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,female,irregular
1,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,"female, female",irregular
2,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,female,bullet
3,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,female,irregular
4,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,female,monthly

In [ ]:
# Se analizan todas las columnas de tipo object (texto)
# para detectar posibles problemas de formato relacionados con espacios.

df_kiva.select_dtypes(include='object').apply(

    # Para cada columna se evalúan tres posibles problemas:
    lambda col: col.str.contains(
        r'^\s|\s$|\s{2,}',  # 1. espacios al inicio (^\\s)
                            # 2. espacios al final (\\s$)
                            # 3. múltiples espacios internos (\\s{2,})
        na=False
    ).sum()

).sort_values(ascending=False)

use                   56253
region                 3713
activity                  0
country_code              0
sector                    0
country                   0
currency                  0
borrower_genders          0
repayment_interval        0
dtype: int64

In [ ]:
# Aplicación de limpieza de espacios en todas las columnas de texto
for col in df_kiva.select_dtypes(include='object').columns:
    df_kiva[col] = (
        df_kiva[col]
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )

In [ ]:
# Se realiza una verificación posterior al proceso de limpieza
# para confirmar que se han eliminado los problemas de formato

df_kiva.select_dtypes(include='object').apply(
    lambda col: col.str.contains(
        r'^\s|\s$|\s{2,}',
        na=False
    ).sum()

).sort_values(ascending=False)

activity              0
sector                0
use                   0
country_code          0
country               0
region                0
currency              0
borrower_genders      0
repayment_interval    0
dtype: int64

Se realiza una validación previa y posterior al proceso de limpieza de las columnas de tipo texto del dataset. En primer lugar, se detectan posibles inconsistencias relacionadas con espacios en blanco, incluyendo espacios al inicio, al final y múltiples espacios consecutivos dentro de los textos. Posteriormente, se aplica un proceso de limpieza global utilizando `strip()` y una expresión regular para normalizar los espacios. Finalmente, se repite la validación inicial para confirmar la efectividad de la transformación, verificando la reducción de incidencias detectadas.

In [ ]:
# Se identifican las columnas de tipo 'object' para normalizar y limpiar cada una de ellas
df_kiva.select_dtypes(include='object').columns

Index(['activity', 'sector', 'use', 'country_code', 'country', 'region',
       'currency', 'borrower_genders', 'repayment_interval'],
      dtype='object')

In [ ]:
# Categorias en 'activity'
df_kiva['activity'].value_counts()

activity
Farming                      72622
General Store                64517
Personal Housing Expenses    32295
Food Production/Sales        27906
Agriculture                  26690
                             ...
Film                            12
Personal Care Products           7
Event Planning                   5
Celebrations                     5
Adult Care                       2
Name: count, Length: 163, dtype: int64

In [ ]:
# Comparación entre valores originales y versión en minúsculas
# para detectar posibles duplicados ocultos por formato

df_kiva['activity'].str.lower().nunique(), df_kiva['activity'].nunique()

(163, 163)

In [ ]:
# Se normaliza la columna activity a formato título
df_kiva['activity'] = df_kiva['activity'].str.title()

In [ ]:
# Categorias en 'sector'
df_kiva['sector'].value_counts()

sector
Agriculture       179224
Food              135749
Retail            123758
Services           44699
Personal Use       36247
Housing            33571
Clothing           32480
Education          30837
Transportation     15455
Arts               11994
Health              9172
Construction        6194
Manufacturing       6158
Entertainment        820
Wholesale            626
Name: count, dtype: int64

In [ ]:
df_kiva['sector'].str.lower().nunique(), df_kiva['sector'].nunique()

(15, 15)

In [ ]:
# Se normaliza la columna 'sector' a formato título
df_kiva['sector'] = df_kiva['sector'].str.title()

In [ ]:
# Categorias en 'use'
df_kiva['use'].value_counts()

use
to buy a water filter to provide safe drinking water for their family.    5350
to buy a water filter to provide safe drinking water for her family.      4165
To buy a water filter to provide safe drinking water for their family.    3202
to build a sanitary toilet for her family.                                1709
to build a sanitary toilet for her family                                 1599
                                                                          ...
to buy materials to finish making canoes and to buy fish.                    1
to purchase food products and start a new business                           1
to expand her existing poultry farm business.                                1
To buy a sewing machine, lace, zippers and buttons                           1
to buy more cosmetics products for her beauty parlor.                        1
Name: count, Length: 416583, dtype: int64

In [ ]:
df_kiva['use'].str.lower().nunique(), df_kiva['use'].nunique()

(411516, 416583)

In [ ]:
# Quitamos los puntos finales de la columna 'use'
df_kiva['use'] = df_kiva['use'].str.rstrip('.')

In [ ]:
# Capitalizamos la primera letra de la columna 'use
df_kiva['use'] = df_kiva['use'].str.capitalize()

In [ ]:
df_kiva['use'].str.lower().nunique(), df_kiva['use'].nunique()

(396049, 396049)

In [ ]:
# Categorias en 'country_code'
df_kiva['country_code'].value_counts()

country_code
PH    160361
KE     75113
SV     39321
KH     34811
PK     26853
       ...
VI         2
MR         1
GU         1
CI         1
BT         1
Name: count, Length: 86, dtype: int64

In [ ]:
df_kiva['country_code'].str.lower().nunique(), df_kiva['country_code'].nunique()

(86, 86)

In [ ]:
# Ponemos en mayúscula la columna 'country_code'
df_kiva['country_code'] = df_kiva['country_code'].str.upper()

In [ ]:
# Categorias en 'country'
df_kiva['country'].value_counts()

country
Philippines       160361
Kenya              75113
El Salvador        39321
Cambodia           34811
Pakistan           26853
                   ...
Virgin Islands         2
Mauritania             1
Guam                   1
Cote D'Ivoire          1
Bhutan                 1
Name: count, Length: 87, dtype: int64

In [ ]:
df_kiva['country'].str.lower().nunique(), df_kiva['country'].nunique()

(87, 87)

In [ ]:
# Se normaliza la columna 'country' a formato título
df_kiva['country'] = df_kiva['country'].str.title()

In [ ]:
# Categorias en 'region'
df_kiva['region'].value_counts()

region
Unknown                                       52579
Kaduna                                        10000
Lahore                                         7178
Rawalpindi                                     4496
Cusco                                          3841
                                              ...
Villa Rey, Echague, Isabela                       1
Nunisi                                            1
Batibut, Sapang Dalaga, Misamis Occidental        1
Peque                                             1
Pueblo Nuevo - Chepén - La Libertad               1
Name: count, Length: 12669, dtype: int64

In [ ]:
df_kiva['region'].str.lower().nunique(), df_kiva['region'].nunique()

(12640, 12669)

In [ ]:
# Se normaliza la columna 'region' a formato título
df_kiva['region'] = df_kiva['region'].str.title()

In [ ]:
df_kiva['region'].str.lower().nunique(), df_kiva['region'].nunique()

(12640, 12640)

In [ ]:
# Categorias en 'currency'
df_kiva['currency'].value_counts()

currency
PHP    160360
USD    104431
KES     74616
KHR     29487
PKR     26852
        ...
XCD        16
CLP         8
NAD         8
VUV         4
ZWD         1
Name: count, Length: 67, dtype: int64

In [ ]:
df_kiva['currency'].str.lower().nunique(), df_kiva['currency'].nunique()

(67, 67)

In [ ]:
# Ponemos en mayúscula la columna 'currency'
df_kiva['currency'] = df_kiva['currency'].str.upper()

In [ ]:
# Categorias en 'borrower_genders'
df_kiva['borrower_genders'].value_counts()

borrower_genders
female                                                                                                                                                                                                426502
male                                                                                                                                                                                                  134710
female, female                                                                                                                                                                                         12164
female, female, female                                                                                                                                                                                 11676
female, female, female, female                                                                                                                                                                          9052
                                                                                                                                                                                                       ...
female, female, male, female, male, male, female, male, male, male, male, male, female, male, male, female, male, female, female, female, male, female                                                     1
female, male, female, female, male, female, female, female, female, female, female, female, female, female, female, female, female                                                                         1
male, female, male, female, female, female, female, female, female, female, female, female, female, female, male, female, female, female, female, female, male, male, female, female, female, male         1
female, female, male, female, female, female, female, female, female, female, male, male, female, female, male, female, female, female, female, male, female, male, female                                 1
male, female, male, female, female, male, male, female, female, female, female, female, female, female, female, male, male, male, female, male, female, male                                               1
Name: count, Length: 11298, dtype: int64

In [ ]:
df_kiva['borrower_genders'].str.lower().nunique(), df_kiva['borrower_genders'].nunique()

(11298, 11298)

In [ ]:
# Ponemos en minúscula la columna 'borrower_genders'
df_kiva['borrower_genders'] = df_kiva['borrower_genders'].str.lower()

In [ ]:
# Categorias en 'repayment_interval'
df_kiva['repayment_interval'].value_counts()

repayment_interval
monthly      340171
irregular    256573
bullet        69638
weekly          602
Name: count, dtype: int64

In [ ]:
df_kiva['repayment_interval'].str.lower().nunique(), df_kiva['repayment_interval'].nunique()

(4, 4)

In [ ]:
# Ponemos en minúscula la columna 'repayment interval'
df_kiva['repayment_interval'] = df_kiva['repayment_interval'].str.lower()

In [ ]:
# Visualización final
df_kiva.select_dtypes(include='object').head(10)

,activity,sector,use,country_code,country,region,currency,borrower_genders,repayment_interval
0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell",PK,Pakistan,Lahore,PKR,female,irregular
1,Rickshaw,Transportation,To repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,"female, female",irregular
2,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,female,bullet
3,Embroidery,Arts,To purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,female,irregular
4,Milk Sales,Food,To purchase one buffalo,PK,Pakistan,Abdul Hakeem,PKR,female,monthly
5,Services,Services,Purchase leather for my business using ksh 20000,KE,Kenya,Unknown,KES,female,irregular
6,Dairy,Agriculture,To purchase a dairy cow and start a milk produ...,IN,India,Maynaguri,INR,female,bullet
7,Beauty Salon,Services,To buy more hair and skin care products,PK,Pakistan,Ellahabad,PKR,female,monthly
8,Manufacturing,Manufacturing,"To purchase leather, plastic soles and heels i...",PK,Pakistan,Lahore,PKR,female,monthly
9,Food Production/Sales,Food,"To buy a stall, gram flour, ketchup, and coal ...",PK,Pakistan,Lahore,PKR,female,irregular

Se realiza una comparación del número de valores únicos antes y después de aplicar normalización a minúsculas para detectar posibles duplicados implícitos por inconsistencias de formato. El análisis muestra que únicamente las columnas `use` y `region` presentan variaciones significativas, indicando presencia de duplicados derivados de diferencias en la escritura. Aun así, se ha aplicado un proceso de limpieza y estandarización en todas las columnas de tipo texto para garantizar un formato homogéneo en el dataset.

In [ ]:
# Se identifican los registros donde el importe financiado supera el importe del préstamo
df_incoherentes = df_kiva[df_kiva['funded_amount'] > df_kiva['loan_amount']]

In [ ]:
# Tamaño del problema
df_incoherentes.shape

(2, 17)

In [ ]:
# Se eliminan los registros donde el importe financiado supera el importe del préstamo
# ya que incumplen una regla de coherencia del negocio

df_kiva = df_kiva[df_kiva['funded_amount'] <= df_kiva['loan_amount']]

In [ ]:
# Comprobación de que no quedan registros incoherentes
df_kiva[df_kiva['funded_amount'] > df_kiva['loan_amount']].shape

(0, 17)

Se ha validado la coherencia del dataset comprobando que el importe financiado `funded_amount` no supere el importe del préstamo solicitado `loan_amount`, ya que esto supondría una inconsistencia en la lógica de negocio. Tras identificar los registros que incumplían esta condición, se eliminaron del conjunto de datos. Finalmente, se verificó que no quedan casos que violen esta regla, asegurando la integridad y consistencia de los datos para el análisis posterior.

In [ ]:
df_kiva[['funded_amount','loan_amount','lender_count','term_in_months']].describe()

       funded_amount    loan_amount   lender_count  term_in_months
count  666982.000000  666982.000000  666982.000000        666982.0
mean      785.124464     840.298164      20.550794       13.730194
std      1127.996989    1187.908215      28.366130        8.596118
min         0.000000      25.000000       0.000000             1.0
25%       250.000000     275.000000       7.000000             8.0
50%       450.000000     500.000000      13.000000            13.0
75%       900.000000    1000.000000      24.000000            14.0
max    100000.000000  100000.000000    2986.000000           158.0

Se realiza un análisis exploratorio de las principales variables numéricas del dataset con el objetivo de identificar posibles valores atípicos. Mediante estadísticas descriptivas se observan valores extremos en variables como loan_amount y funded_amount, lo que refleja la heterogeneidad natural del sistema de microfinanciación. También se detectan valores elevados en lender_count y, en menor medida, en term_in_months, lo que confirma la variabilidad en la estructura de los préstamos y su financiación.

Dado que estos valores representan casos reales dentro del dominio del problema, se decide no eliminarlos para preservar la representatividad del dataset.